name: 🎉 Release Binary

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest-16-cores

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v4
        with:
          go-version: ">=1.15.0"

      - uses: goreleaser/goreleaser-action@v4
        with:
          args: "release --rm-dist"
          version: latest
        env:
          GITHUB_TOKEN: "${{ secrets.TOKEN }}"
